# Generated by Django 6.0.4 on 2026-05-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('personnel_reallocation', 'Personnel Reallocation'), ('personnel_contract_extension', 'Personnel Contract Extension'), ('generic_text', 'General Request')], max_length=50, verbose_name='Task Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('last_status_change', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='hr.employee')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='hr.employee')),
                ('last_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_tasks', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('file', models.FileField(upload_to='task_attachments/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GenericTextTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Generic Text Task',
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='PersonnelContractExtensionTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('plan_position_number', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('is_limited', models.BooleanField(default=True)),
                ('limitation_reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extension_tasks', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Contract Extension Task',
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='PersonnelReallocationTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('plan_position_number', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reallocation_tasks', to='hr.employee')),
                ('target_wbs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finances.wbselement')),
            ],
            options={
                'verbose_name': 'Personnel Reallocation Task',
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='PurchaseOrderTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('supplier', models.CharField(max_length=200, verbose_name='Supplier')),
                ('wbs_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.wbselement', verbose_name='WBS Element')),
            ],
            options={
                'verbose_name': 'Purchase Order Task',
                'verbose_name_plural': 'Purchase Order Tasks',
            },
            bases=('tasks.task',),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_description', models.TextField(blank=True, verbose_name='Product Description')),
                ('link_to_product', models.URLField(blank=True, verbose_name='Link to Product')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Quantity')),
                ('purchase_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tasks.purchaseordertask')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]


