# Generated by Django 6.0.4 on 2026-05-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordertask',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Order Number'),
        ),
    ]


