# Generated by Django 6.0.4 on 2026-05-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_purchaseordertask_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseordertask',
            name='order_number',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Order Number'),
        ),
    ]


