# Generated by Django 6.0.4 on 2026-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_purchaseordertask_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Task Number'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title'),
        ),
    ]


