# Generated by Django 6.0.4 on 2026-05-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_task_number_alter_task_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelcontractextensiontask',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]


