# Generated by Django 6.0.4 on 2026-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_contract_job_number'),
        ('tasks', '0005_personnelcontractextensiontask_valid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordertask',
            name='archived_by',
            field=models.ManyToManyField(blank=True, related_name='archived_purchase_orders', to='hr.employee', verbose_name='Archived by users'),
        ),
    ]


