# Generated by Django 6.0.4 on 2026-05-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_add_updated_at_to_standardpurchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpurchaseitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
    ]


