# Generated by Django 6.0.4 on 2026-06-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_move_archived_by_to_base_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordertask',
            name='at_beleg_nummer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='AT - Beleg Nummer'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]


