# Generated by Django 6.0.4 on 2026-07-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_purchaseordertask_at_beleg_nummer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseordertask',
            options={'permissions': [('create_purchase_order', 'Can create purchase orders'), ('view_all_purchase_orders', 'Can view all purchase orders'), ('change_wbs_on_purchase_order', 'Can change WBS element on purchase orders'), ('create_personnel_task', 'Can create personnel tasks'), ('create_general_request', 'Can create general requests')], 'verbose_name': 'Purchase Order Task', 'verbose_name_plural': 'Purchase Order Tasks'},
        ),
        migrations.AlterModelOptions(
            name='standardpurchaseitem',
            options={'ordering': ['supplier', 'product_name'], 'permissions': [('view_standard_order', 'Can view standard orders'), ('manage_standard_order', 'Can manage standard orders')], 'verbose_name': 'Standard Purchase Item', 'verbose_name_plural': 'Standard Purchase Items'},
        ),
    ]
