# Generated by Django 6.0.4 on 2026-07-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_payscale_options_alter_wbselement_options_and_more'),
        ('hr', '0007_personnel_recruitment_and_document_versions'),
        ('tasks', '0014_merge_approval_permission_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order'), ('personnel_reallocation', 'Personnel Reallocation'), ('personnel_contract_extension', 'Personnel Contract Extension'), ('personnel_recruitment', 'Personnel Recruitment'), ('generic_text', 'General Request')], max_length=50, verbose_name='Task Type'),
        ),
        migrations.CreateModel(
            name='PersonnelRecruitmentTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tasks.task')),
                ('prefix', models.CharField(blank=True, max_length=20, verbose_name='Prefix / Title')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('country_of_origin', models.CharField(max_length=100, verbose_name='Country of Origin')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name='Place of Birth')),
                ('email_professional', models.EmailField(max_length=254, verbose_name='Professional Email')),
                ('private_phone_number', models.CharField(max_length=30, verbose_name='Private Phone')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('house_number', models.CharField(max_length=20, verbose_name='House Number')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Germany', max_length=100, verbose_name='Country')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('plan_position_number', models.CharField(max_length=50, verbose_name='Plan Position Number')),
                ('valid_from', models.DateField(verbose_name='Contract Start Date')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Contract End Date')),
                ('application_file', models.FileField(upload_to='recruitment_tasks/application/', verbose_name='Application')),
                ('cv_file', models.FileField(upload_to='recruitment_tasks/cv/', verbose_name='Curriculum Vitae')),
                ('measles_proof_file', models.FileField(upload_to='recruitment_tasks/measles/', verbose_name='Measles Vaccination Proof')),
                ('created_employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_source_task', to='hr.employee', verbose_name='Created Employee')),
                ('wbs_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_tasks', to='finances.wbselement', verbose_name='WBS Element')),
            ],
            options={
                'verbose_name': 'Personnel Recruitment Task',
            },
            bases=('tasks.task',),
        ),
    ]
