# Generated by Django 6.0.4 on 2026-07-03 09:42

import decimal

import django.db.models.deletion
from django.db import migrations, models


def migrate_recruitment_wbs_to_allocations(apps, schema_editor):
    PersonnelRecruitmentTask = apps.get_model('tasks', 'PersonnelRecruitmentTask')
    RecruitmentFundingAllocation = apps.get_model('tasks', 'RecruitmentFundingAllocation')

    for task in PersonnelRecruitmentTask.objects.exclude(wbs_element_id=None):
        RecruitmentFundingAllocation.objects.create(
            recruitment_task=task,
            wbs_element_id=task.wbs_element_id,
            weekly_hours_allocated=decimal.Decimal('39.00'),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_payscale_options_alter_wbselement_options_and_more'),
        ('tasks', '0015_personnel_recruitment_and_document_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentFundingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('weekly_hours_allocated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weekly Working Hours')),
                ('recruitment_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_allocations', to='tasks.personnelrecruitmenttask', verbose_name='Recruitment Task')),
                ('wbs_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.wbselement', verbose_name='WBS Element')),
            ],
            options={
                'verbose_name': 'Recruitment Funding Allocation',
                'verbose_name_plural': 'Recruitment Funding Allocations',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(migrate_recruitment_wbs_to_allocations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='personnelrecruitmenttask',
            name='wbs_element',
        ),
        migrations.AlterField(
            model_name='personnelrecruitmenttask',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], default='X', max_length=1, verbose_name='Gender'),
        ),
    ]