# Generated by Django 6.0.4 on 2026-07-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_recruitment_funding_allocations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelrecruitmenttask',
            name='plan_position_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Plan Position Number'),
        ),
    ]
