# Generated by Django 6.0.4 on 2026-07-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employee_job'),
        ('tasks', '0020_rename_recruitment_email_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_workgroup',
            field=models.ForeignKey(blank=True, help_text='Workgroup of the creator at task creation time.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='hr.workgroup', verbose_name='Creator Workgroup'),
        ),
        migrations.CreateModel(
            name='TaskWorkflowCoordinator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('task_type', models.CharField(choices=[('purchase_order', 'Purchase Order'), ('personnel_reallocation', 'Personnel Reallocation'), ('personnel_contract_extension', 'Personnel Contract Extension'), ('personnel_recruitment', 'Personnel Recruitment'), ('generic_text', 'General Request')], max_length=50, verbose_name='Task Type')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_workflow_coordinator_assignments', to='hr.employee', verbose_name='Coordinator')),
                ('workgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_workflow_coordinators', to='hr.workgroup', verbose_name='Workgroup')),
            ],
            options={
                'verbose_name': 'Task Workflow Coordinator',
                'verbose_name_plural': 'Task Workflow Coordinators',
                'ordering': ['workgroup__short_name', 'task_type', 'coordinator__last_name'],
                'constraints': [models.UniqueConstraint(fields=('workgroup', 'task_type', 'coordinator'), name='unique_task_workflow_coordinator')],
            },
        ),
    ]
