# Generated by Django 6.0.4 on 2026-07-15 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_task_comment_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomment',
            options={'ordering': ['created_at']},
        ),
    ]
