# Generated by Django 6.0.4 on 2026-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_taskcomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelrecruitmenttask',
            name='experience_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Experience Level'),
        ),
        migrations.AddField(
            model_name='personnelrecruitmenttask',
            name='pay_scale_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pay Scale Group'),
        ),
    ]
