# Generated by Django 6.0.4 on 2026-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_personnel_recruitment_payscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelrecruitmenttask',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Salary (€)'),
        ),
        migrations.AddField(
            model_name='personnelrecruitmenttask',
            name='working_as',
            field=models.CharField(blank=True, max_length=200, verbose_name='Working As'),
        ),
    ]
