# Generated by Django 6.0.4 on 2026-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_contact_person_comments'),
        ('tasks', '0029_purchaseordertask_sap_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reallocationfundingallocation',
            name='reallocation_funding_allocation_one_target',
        ),
        migrations.AddField(
            model_name='purchaseordertask',
            name='import_completed',
            field=models.BooleanField(default=False, help_text='True when imported data confirms the administration process for this purchase order is complete.', verbose_name='Import completed'),
        ),
        migrations.AddConstraint(
            model_name='reallocationfundingallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost_center__isnull', True), ('wbs_element__isnull', False)), models.Q(('cost_center__isnull', False), ('wbs_element__isnull', True)), _connector='OR'), name='reallocation_funding_allocation_one_target'),
        ),
    ]
