# Generated by Django 6.0.4 on 2026-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_import_completed_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentjob',
            name='estimated_monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed theoretical monthly salary for 100% workload when no TV-L group/level is set. Mutually exclusive with TV-L defaults.', max_digits=10, null=True, verbose_name='Estimated monthly salary (€)'),
        ),
        migrations.AlterField(
            model_name='personnelrecruitmenttask',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Theoretical Monthly Salary for 100% Workload'),
        ),
    ]
