# Generated by Django 6.0.4 on 2026-07-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_recruitment_job_estimated_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentjob',
            name='help_text',
            field=models.TextField(blank=True, default='', help_text='Shown in the recruitment form when this job is selected.', verbose_name='Help text'),
        ),
    ]
