# Generated by Django 6.0.4 on 2026-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_recruitment_job_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='cas_number',
            field=models.CharField(blank=True, default='', help_text='Optional. If a hazardous CAS is entered, a chemical inventory draft is created.', max_length=32, verbose_name='CAS number'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='delivered',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Delivered'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivered at'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='is_dangerous',
            field=models.BooleanField(db_index=True, default=False, help_text='Set automatically from free chemical databases and institute threshold.', verbose_name='Hazardous substance (Gefahrstoff)'),
        ),
    ]
