# Generated by Django 6.0.4 on 2026-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_chemicals_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='delivered_number',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative quantity received so far (partial deliveries allowed).', verbose_name='Delivered number'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='delivered',
            field=models.BooleanField(db_index=True, default=False, help_text='True when delivered_number equals quantity (fully delivered).', verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='First time a positive delivery was recorded.', null=True, verbose_name='Delivered at'),
        ),
    ]
