# Generated by Django 6.0.4

from django.db import migrations, models


DEFAULT_OPTIONAL_FIELDS = {
    'prefix',
    'gender',
    'private_phone_number',
    'qualification',
    'limitation_reason',
    'working_as',
    'pay_scale_group',
    'experience_level',
    'monthly_salary',
    'weekly_hours',
}

STANDARD_FIELDS = [
    'prefix', 'first_name', 'last_name', 'gender', 'date_of_birth',
    'country_of_origin', 'place_of_birth', 'street', 'house_number',
    'postal_code', 'city', 'country', 'email_private', 'private_phone_number',
    'qualification', 'job', 'working_as', 'pay_scale_group', 'experience_level',
    'weekly_hours', 'monthly_salary', 'valid_from', 'valid_until',
    'limitation_reason', 'cv_file', 'latest_degree_certificate_file',
    'funding_allocations',
]


def create_standard_job(apps, schema_editor):
    RecruitmentJob = apps.get_model('tasks', 'RecruitmentJob')
    RecruitmentJobFieldRule = apps.get_model('tasks', 'RecruitmentJobFieldRule')

    job = RecruitmentJob.objects.filter(is_standard=True).first()
    if job is None:
        job, _created = RecruitmentJob.objects.get_or_create(
            name='Standard',
            defaults={'is_active': True, 'is_standard': True},
        )
        job.is_standard = True
        job.is_active = True
        job.save()

    for field_key in STANDARD_FIELDS:
        visibility_mode = 'always'
        trigger = ''
        if field_key == 'limitation_reason':
            visibility_mode = 'when_field_set'
            trigger = 'valid_until'
        required_mode = 'never' if field_key in DEFAULT_OPTIONAL_FIELDS else 'always'
        RecruitmentJobFieldRule.objects.update_or_create(
            job=job,
            field_key=field_key,
            defaults={
                'visibility_mode': visibility_mode,
                'visibility_trigger_field': trigger,
                'required_mode': required_mode,
            },
        )

    for other in RecruitmentJob.objects.filter(is_standard=False):
        for rule in other.field_rules.all():
            changed = False
            if rule.visibility_mode == 'always' and not rule.visibility_duration_months:
                rule.visibility_mode = 'inherit'
                changed = True
            default_required = 'never' if rule.field_key in DEFAULT_OPTIONAL_FIELDS else 'always'
            if rule.required_mode == default_required and not rule.required_duration_months:
                rule.required_mode = 'inherit'
                changed = True
            if changed:
                rule.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_purchaseitem_delivered_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentjob',
            name='is_standard',
            field=models.BooleanField(
                default=False,
                help_text='Hidden template job. Other jobs inherit unset field rules from this job.',
                verbose_name='Standard job',
            ),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='dropdown_help_text',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Shown when hovering a job in the recruitment job dropdown.',
                verbose_name='Dropdown hover text',
            ),
        ),
        migrations.AddField(
            model_name='recruitmentjobfieldrule',
            name='visibility_trigger_field',
            field=models.CharField(
                blank=True,
                default='',
                max_length=50,
                verbose_name='Visible when this field is set',
            ),
        ),
        migrations.AddField(
            model_name='recruitmentjobfieldrule',
            name='help_text',
            field=models.TextField(blank=True, default='', verbose_name='Field help text'),
        ),
        migrations.AlterField(
            model_name='recruitmentjobfieldrule',
            name='visibility_mode',
            field=models.CharField(
                choices=[
                    ('inherit', 'Use Standard'),
                    ('always', 'Always visible'),
                    ('never', 'Never visible'),
                    ('when_duration', 'Visible when duration matches'),
                    ('when_field_set', 'Visible when field X is set'),
                ],
                default='always',
                max_length=20,
                verbose_name='Visibility',
            ),
        ),
        migrations.AlterField(
            model_name='recruitmentjobfieldrule',
            name='required_mode',
            field=models.CharField(
                choices=[
                    ('inherit', 'Use Standard'),
                    ('never', 'Optional'),
                    ('always', 'Always required'),
                    ('when_duration', 'Required when duration matches'),
                ],
                default='never',
                max_length=20,
                verbose_name='Required',
            ),
        ),
        migrations.AddField(
            model_name='personnelrecruitmenttask',
            name='qualification',
            field=models.TextField(blank=True, verbose_name='Qualification'),
        ),
        migrations.AlterField(
            model_name='personnelrecruitmenttask',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Contract End Date'),
        ),
        migrations.RunPython(create_standard_job, noop_reverse),
        migrations.AddConstraint(
            model_name='recruitmentjob',
            constraint=models.UniqueConstraint(
                condition=models.Q(is_standard=True),
                fields=('is_standard',),
                name='unique_standard_recruitment_job',
            ),
        ),
    ]
