# Generated by Django 6.0.4 on 2026-08-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_reallocationfundingallocation_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelrecruitmenttask',
            name='weekly_hours',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Weekly Working Hours'),
        ),
    ]
