# Generated by Django 6.0.4 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0028_contract_weekly_hours_3dp'),
        ('tasks', '0037_recruitment_weekly_hours_3dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(
                choices=[
                    ('purchase_order', 'Purchase Order'),
                    ('personnel_reallocation', 'Personnel Reallocation'),
                    ('personnel_contract_extension', 'Personnel Contract Extension'),
                    ('personnel_recruitment', 'Personnel Recruitment'),
                    ('personnel_change_working_hours', 'Change Working Hours'),
                    ('generic_text', 'General Request'),
                ],
                max_length=50,
                verbose_name='Task Type',
            ),
        ),
        migrations.AlterField(
            model_name='taskworkflowcoordinator',
            name='task_type',
            field=models.CharField(
                choices=[
                    ('purchase_order', 'Purchase Order'),
                    ('personnel_reallocation', 'Personnel Reallocation'),
                    ('personnel_contract_extension', 'Personnel Contract Extension'),
                    ('personnel_recruitment', 'Personnel Recruitment'),
                    ('personnel_change_working_hours', 'Change Working Hours'),
                    ('generic_text', 'General Request'),
                ],
                max_length=50,
                verbose_name='Task Type',
            ),
        ),
        migrations.CreateModel(
            name='PersonnelChangeWorkingHoursTask',
            fields=[
                ('task_ptr', models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='tasks.task',
                )),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('new_weekly_hours', models.DecimalField(
                    decimal_places=3,
                    max_digits=6,
                    verbose_name='New weekly working hours',
                )),
                ('employee', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='change_working_hours_tasks',
                    to='hr.employee',
                )),
            ],
            options={
                'verbose_name': 'Change Working Hours Task',
            },
            bases=('tasks.task',),
        ),
    ]
