# Generated by Django 6.0.4 on 2026-09-16 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_ensure_cost_center_manage_all_perm'),
        ('tasks', '0039_taskinitialopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnelcontractextensiontask',
            name='project_description_file',
            field=models.FileField(blank=True, null=True, upload_to='extension_tasks/project_description/', verbose_name='Project Description'),
        ),
        migrations.CreateModel(
            name='ExtensionFundingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('workhours_percentage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Percentage of Workhours')),
                ('plan_position_number', models.CharField(blank=True, max_length=50, verbose_name='Plan Position Number')),
                ('job_number', models.CharField(blank=True, max_length=50, verbose_name='Job Number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extension_funding_allocations', to='finances.costcenter', verbose_name='Cost Center')),
                ('extension_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_allocations', to='tasks.personnelcontractextensiontask', verbose_name='Contract Extension Task')),
                ('wbs_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.wbselement', verbose_name='WBS Element')),
            ],
            options={
                'verbose_name': 'Extension Funding Allocation',
                'verbose_name_plural': 'Extension Funding Allocations',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('cost_center__isnull', True), ('wbs_element__isnull', False)), models.Q(('cost_center__isnull', False), ('wbs_element__isnull', True)), _connector='OR'), name='extension_funding_allocation_one_target')],
            },
        ),
    ]
