# Generated by Django 6.0.4 on 2026-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_extension_funding_and_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionfundingallocation',
            name='source_allocation_id',
            field=models.PositiveIntegerField(blank=True, help_text='Employee funding allocation this row was copied from.', null=True, verbose_name='Source allocation id'),
        ),
        migrations.AddField(
            model_name='personnelcontractextensiontask',
            name='original_funding_snapshot',
            field=models.JSONField(blank=True, default=list, help_text='Employee funding allocations as they were when this extension was created.', verbose_name='Original funding snapshot'),
        ),
    ]
