# Generated by Django 6.0.4 on 2026-09-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_occupation_salary_tables'),
        ('tasks', '0041_extension_funding_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentjob',
            name='occupation_weekly_hours',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Default weekly hours (occupational table)'),
        ),
        migrations.AddField(
            model_name='recruitmentjob',
            name='salary_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_jobs', to='core.occupationsalarytable', verbose_name='Occupational salary table'),
        ),
    ]
