# Generated by Django 6.0.4 on 2026-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginPopupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('trigger', models.CharField(choices=[('first_login', 'First login (welcome / profile completion)'), ('contract_ending_soon', 'Own contract ending in X months'), ('any_contract_ending_soon', 'Any employee contract ending in X months'), ('new_task_assigned', 'New task assigned to the user'), ('task_status_changed', 'Status changed on a task created by the user'), ('login_after_datetime', 'Login after specific date/time')], max_length=50)),
                ('reaction_type', models.CharField(choices=[('popup', 'Show Popup')], default='popup', max_length=20)),
                ('text', models.TextField(help_text='Message text for popup or email.')),
                ('link_to', models.CharField(blank=True, choices=[('', 'Just OK (no redirect)'), ('my_profile', 'My Profile'), ('my_tasks', 'My Tasks'), ('employee_list', 'Employees List'), ('psp_elements', 'PSP Elements'), ('workgroup_list', 'Working Groups'), ('location_management', 'Manage Locations')], help_text='For popup: where to redirect on OK.', max_length=50)),
                ('x_months', models.PositiveIntegerField(blank=True, help_text="For 'contract_ending_soon' or 'any_contract_ending_soon' trigger.", null=True)),
                ('trigger_datetime', models.DateTimeField(blank=True, help_text="For 'login_after_datetime' trigger.", null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Login Popup Config',
                'verbose_name_plural': 'Login Popup Configs',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_login_welcome_shown',
            field=models.BooleanField(default=False, verbose_name='First Login Welcome Popup Shown'),
        ),
    ]
