# Generated by Django 6.0.4 on 2026-07-02 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginpopupconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginpopupconfig',
            name='shown_to_users',
            field=models.ManyToManyField(blank=True, help_text='Users who have already seen this popup.', related_name='shown_login_popups', to=settings.AUTH_USER_MODEL, verbose_name='Shown to users'),
        ),
    ]
