# Generated by Django 6.0.4 on 2026-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_loginpopupconfig_link_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpopupconfig',
            name='link_to',
            field=models.CharField(blank=True, choices=[('', 'Just OK (no redirect)'), ('my_profile', 'My Profile'), ('my_tasks', 'My Tasks'), ('employee_list', 'Employees List'), ('psp_elements', 'PSP Elements'), ('workgroup_list', 'Working Groups'), ('location_management', 'Manage Locations'), ('my_checklists', 'My Checklists'), ('chemical_items', 'Chemicals - My Chemical Items'), ('chemical_undelivered', 'Chemicals - Undelivered Order Items')], help_text='For popup: where to redirect on OK.', max_length=50),
        ),
        migrations.AlterField(
            model_name='loginpopupconfig',
            name='trigger',
            field=models.CharField(choices=[('first_login', 'First login (welcome / profile completion)'), ('contract_ending_soon', 'Own contract ending in X months'), ('any_contract_ending_soon', 'Any employee contract ending in X months'), ('new_task_assigned', 'New task assigned to the user'), ('task_status_changed', 'Status changed on a task created by the user'), ('task_comment_on_created_task', 'New message on a task created by the user (by someone else)'), ('login_after_datetime', 'Login after specific date/time'), ('checklist_assigned', 'New checklist assigned to the user'), ('chemical_item_incomplete', 'Chemicals: own chemical item missing required inventory data'), ('chemical_item_delivered', 'Chemicals: own chemical item was delivered (complete inventory data)')], max_length=50),
        ),
    ]
