# Generated by Django 6.0.4 on 2026-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_chemicals_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpopupconfig',
            name='link_to',
            field=models.CharField(blank=True, choices=[('', 'Just OK (no redirect)'), ('my_profile', 'My Profile'), ('my_tasks', 'My Tasks'), ('employee_list', 'Employees List'), ('psp_elements', 'PSP Elements'), ('workgroup_list', 'Working Groups'), ('location_management', 'Manage Locations'), ('my_checklists', 'My Checklists'), ('chemical_items', 'Chemicals - My Chemical Items'), ('chemical_undelivered', 'Undelivered Order Items (all POs)')], help_text='For popup: where to redirect on OK.', max_length=50),
        ),
    ]
