# Generated by Django 6.0.4 on 2026-08-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_email_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginpopupconfig',
            name='email_html',
            field=models.TextField(blank=True, help_text='HTML email body. Edited on the Messaging page.', verbose_name='Email body (HTML)'),
        ),
        migrations.AlterField(
            model_name='loginpopupconfig',
            name='send_email',
            field=models.BooleanField(default=False, help_text='Send the email template when this trigger fires. Edit subject and body on Messaging.', verbose_name='Send email'),
        ),
        migrations.AlterField(
            model_name='loginpopupconfig',
            name='trigger',
            field=models.CharField(choices=[('first_login', 'First login (welcome / profile completion)'), ('contract_ending_soon', 'Own contract ending in X months'), ('any_contract_ending_soon', 'Any employee contract ending in X months'), ('new_task_assigned', 'New task assigned to the user'), ('purchase_order_created', 'New purchase order (procurement) created'), ('personnel_task_created', 'New personnel task created'), ('task_status_changed', 'Status changed on a task created by the user'), ('task_comment_on_created_task', 'New message on a task created by the user (by someone else)'), ('login_after_datetime', 'Login after specific date/time'), ('checklist_assigned', 'New checklist assigned to the user'), ('chemical_item_incomplete', 'Chemicals: own chemical item missing required inventory data'), ('chemical_item_delivered', 'Chemicals: own chemical item was delivered (complete inventory data)')], max_length=50),
        ),
    ]
