# Generated by Django 6.0.4 on 2026-07-15 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0010_employee_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (EN)')),
                ('name_de', models.CharField(max_length=200, verbose_name='Name (DE)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (EN)')),
                ('description_de', models.TextField(blank=True, verbose_name='Description (DE)')),
            ],
            options={
                'verbose_name': 'Checklist Template',
                'verbose_name_plural': 'Checklist Templates',
                'ordering': ['name_en'],
                'permissions': [('view_checklist', 'Can view checklists'), ('manage_checklist', 'Can manage checklist templates and assignments'), ('view_workgroup_progress', 'Can view checklist progress for own workgroup'), ('view_institute_progress', 'Can view institute-wide checklist progress')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort order')),
                ('node_kind', models.CharField(choices=[('section', 'Section'), ('field', 'Field'), ('radio_option', 'Radio option')], max_length=20, verbose_name='Node kind')),
                ('field_type', models.CharField(blank=True, choices=[('checkbox', 'Checkbox'), ('text', 'Text'), ('textarea', 'Textarea'), ('radio_group', 'Radio group'), ('file', 'File upload'), ('date', 'Date')], max_length=20, verbose_name='Field type')),
                ('choice_key', models.CharField(blank=True, max_length=80, verbose_name='Choice key')),
                ('label_en', models.CharField(blank=True, max_length=255, verbose_name='Label (EN)')),
                ('label_de', models.CharField(blank=True, max_length=255, verbose_name='Label (DE)')),
                ('help_en', models.TextField(blank=True, verbose_name='Help (EN)')),
                ('help_de', models.TextField(blank=True, verbose_name='Help (DE)')),
                ('required_for_completion', models.BooleanField(default=False, verbose_name='Required for completion')),
                ('allow_not_applicable', models.BooleanField(default=False, verbose_name='Allow N/A')),
                ('editable_by_subject', models.BooleanField(default=True, verbose_name='Editable by subject')),
                ('editable_by_coordinators', models.BooleanField(default=True, verbose_name='Editable by coordinators')),
                ('visible_to_subject', models.BooleanField(default=True, verbose_name='Visible to subject')),
                ('file_target', models.CharField(blank=True, choices=[('employee_document', 'Employee document'), ('checklist_storage', 'Checklist storage only')], max_length=30, verbose_name='File target')),
                ('employee_document_type', models.CharField(blank=True, choices=[('application', 'Application / Bewerbung'), ('cv', 'Curriculum Vitae / Lebenslauf'), ('latest_degree_certificate', 'Latest Degree Certificate / Zeugnis des letzten Abschlusses'), ('scan_of_contract', 'Scan of Contract / Vertragsscan'), ('profile_picture', 'Profile Picture / Profilbild')], max_length=30, verbose_name='Employee document type')),
                ('storage_label_en', models.CharField(blank=True, max_length=255, verbose_name='Storage label (EN)')),
                ('storage_label_de', models.CharField(blank=True, max_length=255, verbose_name='Storage label (DE)')),
                ('editable_by_employees', models.ManyToManyField(blank=True, related_name='editable_checklist_nodes', to='hr.employee', verbose_name='Editable by employees')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='checklists.checklisttemplatenode', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Checklist Template Node',
                'verbose_name_plural': 'Checklist Template Nodes',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('deprecated', 'Deprecated')], default='draft', max_length=20, verbose_name='Status')),
                ('completion_mode', models.CharField(choices=[('auto', 'Auto when all required fields fulfilled'), ('coordinator_confirm', 'Coordinator must confirm'), ('anchor_field', 'Complete when anchor field fulfilled')], default='coordinator_confirm', max_length=30, verbose_name='Completion mode')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('anchor_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anchor_for_versions', to='checklists.checklisttemplatenode', verbose_name='Anchor node')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_versions_published', to=settings.AUTH_USER_MODEL, verbose_name='Published by')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='checklists.checklisttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Checklist Template Version',
                'verbose_name_plural': 'Checklist Template Versions',
                'ordering': ['template', '-version_number'],
            },
        ),
        migrations.AddField(
            model_name='checklisttemplatenode',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='checklists.checklisttemplateversion', verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='ChecklistInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20, verbose_name='Status')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned by')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_completed', to=settings.AUTH_USER_MODEL, verbose_name='Completed by')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_instances', to='hr.employee', verbose_name='Subject')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='checklists.checklisttemplateversion', verbose_name='Template version')),
            ],
            options={
                'verbose_name': 'Checklist Instance',
                'verbose_name_plural': 'Checklist Instances',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistAssignmentAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, verbose_name='Acknowledged at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_assignment_acks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_acks', to='checklists.checklistinstance', verbose_name='Instance')),
            ],
            options={
                'verbose_name': 'Checklist Assignment Acknowledgement',
                'verbose_name_plural': 'Checklist Assignment Acknowledgements',
                'constraints': [models.UniqueConstraint(fields=('user', 'instance'), name='checklist_assignment_ack_user_instance_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistFieldResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Boolean value')),
                ('value_text', models.TextField(blank=True, verbose_name='Text value')),
                ('value_choice', models.CharField(blank=True, max_length=80, verbose_name='Choice value')),
                ('not_applicable', models.BooleanField(default=False, verbose_name='Not applicable')),
                ('file', models.FileField(blank=True, null=True, upload_to='checklists/%Y/%m/%d/', verbose_name='File')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='Original filename')),
                ('last_changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_field_changes', to=settings.AUTH_USER_MODEL, verbose_name='Last changed by')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklistinstance', verbose_name='Instance')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklisttemplatenode', verbose_name='Node')),
            ],
            options={
                'verbose_name': 'Checklist Field Response',
                'verbose_name_plural': 'Checklist Field Responses',
                'constraints': [models.UniqueConstraint(fields=('instance', 'node'), name='checklist_response_instance_node_uniq')],
            },
        ),
        migrations.AddConstraint(
            model_name='checklisttemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'version_number'), name='checklist_template_version_number_uniq'),
        ),
    ]
