# Generated by Django 6.0.4 on 2026-07-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplatenode',
            name='node_kind',
            field=models.CharField(choices=[('section', 'Section'), ('field', 'Field'), ('radio_option', 'Radio option'), ('html', 'HTML content')], max_length=20, verbose_name='Node kind'),
        ),
    ]
