# Generated by Django 6.0.4 on 2026-07-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_checklisttemplatenode_node_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklisttemplate',
            options={'default_permissions': (), 'ordering': ['name_en'], 'permissions': [('view_checklist', 'Can view checklists'), ('manage_checklist', 'Can manage checklist templates and assignments'), ('view_workgroup_progress', 'Can view checklist progress for own workgroups'), ('view_institute_progress', 'Can view institute-wide checklist progress (all employees)')], 'verbose_name': 'Checklist Template', 'verbose_name_plural': 'Checklist Templates'},
        ),
    ]
