# Generated by Django 6.0.4 on 2026-09-17 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_editor_archive_and_seen'),
        ('documents', '0003_category_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplatenode',
            name='acknowledge_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checklist_acknowledge_nodes', to='documents.document', verbose_name='Acknowledge document'),
        ),
        migrations.AlterField(
            model_name='checklisttemplatenode',
            name='field_type',
            field=models.CharField(blank=True, choices=[('checkbox', 'Checkbox'), ('text', 'Text'), ('textarea', 'Textarea'), ('radio_group', 'Radio group'), ('file', 'File upload'), ('date', 'Date'), ('acknowledge', 'Acknowledge')], max_length=20, verbose_name='Field type'),
        ),
    ]
