# Generated by Django 6.0.4 on 2026-07-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(help_text='Logical path, e.g. recruitment_tasks/cv/example.pdf', max_length=500, unique=True, verbose_name='Storage Path')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Original Filename')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='Content Type')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Size (bytes)')),
                ('content', models.BinaryField(verbose_name='File Content')),
            ],
            options={
                'verbose_name': 'Stored File',
                'verbose_name_plural': 'Stored Files',
                'ordering': ['-created_at'],
            },
        ),
    ]
