# Generated by Django 6.0.4 on 2026-07-20 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_globalsetting_true_cost_multiplicator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='true_cost_multiplicator',
            field=models.DecimalField(decimal_places=3, default=1.3, help_text='Monthly costs = monthly salary × this factor (default 1.3).', max_digits=5, verbose_name='True-Cost Multiplicator'),
        ),
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('third_party_funding_report', 'Third-party funding report'), ('pay_scale', 'Pay scale / TV-L'), ('cost_center_paste', 'Cost center paste import'), ('wbs_paste', 'WBS element paste import'), ('other', 'Other')], db_index=True, max_length=64, verbose_name='Import kind')),
                ('original_filename', models.CharField(blank=True, default='', help_text='Client filename; may be long.', max_length=500, verbose_name='Original filename')),
                ('file_sha256', models.CharField(blank=True, db_index=True, default='', help_text='Hex digest of the uploaded content (empty for paste-only imports).', max_length=64, verbose_name='File SHA-256')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='File size (bytes)')),
                ('file_created_at', models.DateTimeField(blank=True, help_text='Creation timestamp from Excel/OOXML core properties, if present.', null=True, verbose_name='Document created at')),
                ('file_modified_at', models.DateTimeField(blank=True, help_text='Last-modified timestamp from Excel/OOXML core properties, if present.', null=True, verbose_name='Document modified at')),
                ('report_created_on', models.DateField(blank=True, help_text='Business report creation date from file content (e.g. angelegt am).', null=True, verbose_name='Report created on')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('rejected_duplicate', 'Rejected (duplicate file)')], db_index=True, default='completed', max_length=32, verbose_name='Status')),
                ('summary', models.TextField(blank=True, default='', verbose_name='Summary')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_imports', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'Data import log',
                'verbose_name_plural': 'Data import logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'file_sha256'], name='core_dataim_kind_4353f7_idx'), models.Index(fields=['status', 'created_at'], name='core_dataim_status_b9d92b_idx')],
            },
        ),
    ]
