# Generated by Django 6.0.4 on 2026-07-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_data_import_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimportlog',
            name='beleg_from',
            field=models.DateField(blank=True, help_text='Earliest Belegdatum found on the Personalkosten sheet (heuristic coverage start).', null=True, verbose_name='Beleg period from'),
        ),
        migrations.AddField(
            model_name='dataimportlog',
            name='beleg_to',
            field=models.DateField(blank=True, help_text='Latest Belegdatum found on the Personalkosten sheet (heuristic coverage end).', null=True, verbose_name='Beleg period to'),
        ),
    ]
