# Generated by Django 6.0.4 on 2026-07-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_data_import_log_beleg_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='chemical_hazard_threshold',
            field=models.CharField(choices=[('any_ghs', 'Any GHS signal, H-code, or pictogram'), ('signal_warning_or_danger', 'GHS signal Warning or Danger'), ('signal_danger_only', 'GHS signal Danger only'), ('any_pictogram', 'Any GHS pictogram'), ('any_h_code', 'Any GHS H-code'), ('never', 'Never auto-classify (manual only)')], default='any_ghs', help_text='When a CAS number is looked up (free PubChem data), chemicals meeting this threshold are treated as hazardous substances.', max_length=40, verbose_name='Chemical hazard threshold (Gefahrstoff)'),
        ),
    ]
