# Generated by Django 6.0.4 on 2026-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chemicals_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataimportlog',
            name='beleg_from',
            field=models.DateField(blank=True, help_text='Earliest Belegdatum found on the Personalkosten sheet (informational only; funding reports cover PSP start → report pull date).', null=True, verbose_name='Beleg period from'),
        ),
        migrations.AlterField(
            model_name='dataimportlog',
            name='beleg_to',
            field=models.DateField(blank=True, help_text='Latest Belegdatum found on the Personalkosten sheet (informational only; funding reports cover PSP start → report pull date).', null=True, verbose_name='Beleg period to'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='true_cost_multiplicator',
            field=models.DecimalField(decimal_places=3, default=1.3, help_text='True costs = (100% monthly salary + supplements) × (weekly hours / default weekly hours) × this factor (default 1.3).', max_digits=5, verbose_name='True-Cost Multiplicator'),
        ),
    ]
