# Generated by Django 6.0.4 on 2026-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_salary_true_cost_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='personnel_import_tolerance',
            field=models.DecimalField(decimal_places=4, default=0.025, help_text='Relative tolerance for Personalkosten vs expected true costs (e.g. 0.025 = ±2.5%). January always uses 4% instead.', max_digits=5, verbose_name='Personnel import amount tolerance'),
        ),
    ]
