# Generated by Django 6.0.4 on 2026-07-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_personnel_import_flags_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='irresponsible',
            field=models.BooleanField(default=False, help_text='When enabled, the third-party funding import UI shows an option to force re-import of files that were already uploaded or are older than the latest imported report. Use only for recovery/admin.', verbose_name='Irresponsible mode'),
        ),
    ]
