# Generated by Django 6.0.4 on 2026-08-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_globalsetting_configure_email_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='holiday_advance_deadline',
            field=models.DateField(blank=True, help_text='Prepared for a later rule that next-year leave must be requested by this date.', null=True, verbose_name='Advance-request deadline (not enforced yet)'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holiday_email_html',
            field=models.TextField(blank=True, verbose_name='Holiday PDF email body (HTML)'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holiday_email_recipients',
            field=models.TextField(blank=True, help_text='Comma-separated addresses that receive the signed PDF after approval.', verbose_name='Holiday PDF email recipients'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holiday_email_subject',
            field=models.CharField(blank=True, default='Holiday request', max_length=200, verbose_name='Holiday PDF email subject'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holiday_federal_state',
            field=models.CharField(blank=True, default='', help_text='Used for state-specific public holidays.', max_length=2, verbose_name='Federal state (public holidays)'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holiday_half_day_rounding',
            field=models.CharField(choices=[('up', 'Round half days up'), ('down', 'Round half days down')], default='up', max_length=8, verbose_name='Half-day entitlement rounding'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holidays_approval_enabled',
            field=models.BooleanField(default=False, help_text='Workgroup / super approvers decide requests; signed PDF is emailed.', verbose_name='Holidays: approval'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holidays_gantt_enabled',
            field=models.BooleanField(default=False, help_text='Shared approved leave on a team timeline (requires consent).', verbose_name='Holidays: Gantt overview'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='holidays_planning_enabled',
            field=models.BooleanField(default=False, help_text='Employees can request leave, see remaining days, and print an unsigned form.', verbose_name='Holidays: planning'),
        ),
    ]
