# Generated by Django 6.0.4 on 2026-08-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_holiday_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='holidays_enabled',
            field=models.BooleanField(default=True, help_text='Master switch. When off, all holiday menus and pages are hidden; the options below are ignored.', verbose_name='Holidays module'),
        ),
    ]
