# Generated by Django 6.0.4 on 2026-09-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_chemicals_module_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationSalaryTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Occupational salary table',
                'verbose_name_plural': 'Occupational salary tables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OccupationSalaryRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('weekly_hours', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Weekly hours')),
                ('monthly_salary', models.DecimalField(decimal_places=2, help_text='Monthly pay for this weekly working time (not a 100% reference).', max_digits=10, verbose_name='Monthly salary')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.occupationsalarytable', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Occupational salary row',
                'verbose_name_plural': 'Occupational salary rows',
                'ordering': ['weekly_hours'],
                'constraints': [models.UniqueConstraint(fields=('table', 'weekly_hours'), name='occupation_salary_row_hours_uniq')],
            },
        ),
    ]
