# Generated by Django 6.0.4 on 2026-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_holiday_email_variable_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='google_calendar_connected_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Google Calendar connected account'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='google_calendar_enabled',
            field=models.BooleanField(default=False, help_text='When on, employees with a Google Account get writer access to the institute calendar. Access is removed when the address changes or the employee is archived. Turning this off stops further changes; existing shares are left as they are.', verbose_name='Google Calendar sharing'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='From Google Calendar → Settings and sharing → Integrate calendar. The connected Google account must own this calendar.', max_length=255, verbose_name='Google Calendar ID'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='google_calendar_refresh_token',
            field=models.TextField(blank=True, default='', verbose_name='Google Calendar refresh token'),
        ),
    ]
