# Generated by Django 6.0.4 on 2026-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='google_oauth_client_id',
            field=models.CharField(blank=True, default='', help_text='From Google Cloud → APIs & Services → Credentials. OAuth client type: Web application. A non-empty GOOGLE_OAUTH_CLIENT_ID in .env overrides this.', max_length=255, verbose_name='Google OAuth client ID'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='google_oauth_client_secret',
            field=models.CharField(blank=True, default='', help_text='Leave blank to keep the saved secret. Not shown again after saving. A non-empty GOOGLE_OAUTH_CLIENT_SECRET in .env overrides this.', max_length=255, verbose_name='Google OAuth client secret'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='google_calendar_enabled',
            field=models.BooleanField(default=False, help_text='When on, each employee with a Google Account is added as a specific person (writer). The calendar is not made public. Access is removed when the address changes or the employee is archived. Turning this off stops further changes; existing shares are left as they are.', verbose_name='Google Calendar sharing'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='Calendar ID from Google Calendar → Settings and sharing. The calendar can stay private. The connected Google account must own it.', max_length=255, verbose_name='Google Calendar ID'),
        ),
    ]
