# Generated by Django 6.0.4 on 2026-09-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_google_oauth_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='google_service_account_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Google service account email'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='google_service_account_json',
            field=models.TextField(blank=True, default='', help_text='Paste the JSON key from Google Cloud → IAM → Service accounts. Leave blank to keep the saved key. Not shown again after saving. A non-empty GOOGLE_SERVICE_ACCOUNT_JSON or GOOGLE_SERVICE_ACCOUNT_FILE in .env overrides this.', verbose_name='Google service account JSON key'),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='google_calendar_id',
            field=models.CharField(blank=True, default='', help_text='Calendar ID from Google Calendar → Settings and sharing. The calendar can stay private. Share it with the service account as "Make changes and manage sharing".', max_length=255, verbose_name='Google Calendar ID'),
        ),
    ]
