# Generated by Django 6.0.4 on 2026-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_google_service_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='', help_text='THERESE sends as this address. For Sympa it must be a list owner. Should match the SMTP mailbox.', max_length=254, verbose_name='From address'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_host',
            field=models.CharField(blank=True, default='', help_text='e.g. smtp.strato.de. A non-empty EMAIL_HOST in .env overrides all SMTP fields here.', max_length=255, verbose_name='SMTP host'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_password',
            field=models.CharField(blank=True, default='', help_text='Leave blank to keep the saved password. Not shown again after saving.', max_length=255, verbose_name='SMTP password'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_port',
            field=models.PositiveIntegerField(default=465, help_text='465 with SSL, or 587 with STARTTLS.', verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_use_ssl',
            field=models.BooleanField(default=True, help_text='Typical for port 465. Do not combine with STARTTLS.', verbose_name='SMTP SSL (implicit TLS)'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_use_tls',
            field=models.BooleanField(default=False, help_text='Typical for port 587. Keep off when SSL is on.', verbose_name='SMTP STARTTLS'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='smtp_user',
            field=models.CharField(blank=True, default='', help_text='For Strato this is the full mailbox address.', max_length=255, verbose_name='SMTP username'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='sympa_enabled',
            field=models.BooleanField(default=False, help_text='When on, each active institute employee with a professional email is added to the institute list and their workgroup lists. Externals are skipped. Turning this off stops further changes; existing subscriptions are left as they are.', verbose_name='Sympa mailing lists'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='sympa_institute_list',
            field=models.EmailField(blank=True, default='', help_text='e.g. ieecr@listen.uni-bonn.de. All active institute employees are added.', max_length=254, verbose_name='Institute mailing list'),
        ),
        migrations.AddField(
            model_name='globalsetting',
            name='sympa_robot',
            field=models.EmailField(blank=True, default='', help_text='Command mailbox, usually sympa@listen.uni-bonn.de.', max_length=254, verbose_name='Sympa robot address'),
        ),
    ]
