# Generated by Django 6.0.4 on 2026-10-01 12:15

import apps.courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0038_activate_upcoming_funding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('interval_months', models.PositiveIntegerField(blank=True, help_text='Empty = one-time course.', null=True, verbose_name='Repeat every (months)')),
                ('evidence_type', models.CharField(choices=[('certificate', 'Certificate (PDF)'), ('checkbox', 'Checkbox')], default='certificate', max_length=20, verbose_name='Evidence')),
                ('warn_weeks', models.PositiveIntegerField(blank=True, help_text='Empty = no warning window.', null=True, verbose_name='Warn weeks before due')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('all_institute', models.BooleanField(default=False, help_text='Required for non-external employees with a current contract.', verbose_name='All institute')),
                ('extra_employees', models.ManyToManyField(blank=True, related_name='extra_courses', to='hr.employee', verbose_name='Extra employees')),
                ('workgroups', models.ManyToManyField(blank=True, related_name='courses', to='hr.workgroup', verbose_name='Workgroups')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
                'permissions': [('view_institute_course_lists', 'Can view course lists for all employees'), ('view_workgroup_course_lists', 'Can view course lists for own workgroups')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CourseManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('scope', models.CharField(choices=[('institute', 'Institute'), ('workgroup', 'Own workgroups')], default='workgroup', max_length=20, verbose_name='Scope')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_links', to='courses.course', verbose_name='Course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_manager_links', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Course manager',
                'verbose_name_plural': 'Course managers',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_courses', through='courses.CourseManager', to='hr.employee', verbose_name='Managers'),
        ),
        migrations.CreateModel(
            name='CourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('completed_on', models.DateField(verbose_name='Completed on')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('certificate', models.FileField(blank=True, upload_to=apps.courses.models.course_certificate_upload_to, verbose_name='Certificate')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='courses.course', verbose_name='Course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to='hr.employee', verbose_name='Employee')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_course_completions', to=settings.AUTH_USER_MODEL, verbose_name='Recorded by')),
            ],
            options={
                'verbose_name': 'Course completion',
                'verbose_name_plural': 'Course completions',
                'ordering': ['-completed_on', '-pk'],
                'indexes': [models.Index(fields=['course', 'employee', '-completed_on'], name='courses_cou_course__9cb212_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='coursemanager',
            constraint=models.UniqueConstraint(fields=('course', 'employee'), name='course_manager_course_employee_uniq'),
        ),
    ]
