# Generated by Django 6.0.4 on 2026-07-03 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hr', '0007_personnel_recruitment_and_document_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('requires_read_acknowledgement', models.BooleanField(default=False, verbose_name='Requires read acknowledgement')),
                ('audience_match_mode', models.CharField(choices=[('or', 'OR — match any selected criterion'), ('and', 'AND — match all selected criteria')], default='or', max_length=3, verbose_name='Audience match mode')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='targeted_documents', to='auth.group', verbose_name='Target Django groups')),
                ('target_users', models.ManyToManyField(blank=True, related_name='targeted_documents', to=settings.AUTH_USER_MODEL, verbose_name='Target users')),
                ('target_workgroups', models.ManyToManyField(blank=True, related_name='targeted_documents', to='hr.workgroup', verbose_name='Target work groups')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documentcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['title'],
                'permissions': [('view_document', 'Can view documents and SOPs'), ('manage_document', 'Can manage documents and SOPs')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('version_number', models.PositiveIntegerField(verbose_name='Version number')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20, verbose_name='Status')),
                ('content_html', models.TextField(blank=True, verbose_name='Content')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='Change summary')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Document')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions_published', to=settings.AUTH_USER_MODEL, verbose_name='Published by')),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['document', '-version_number'],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('file', models.FileField(upload_to='documents/attachments/%Y/%m/', verbose_name='File')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='documents.documentversion', verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Document Attachment',
                'verbose_name_plural': 'Document Attachments',
                'ordering': ['label', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='documents.document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'Document Activity Log',
                'verbose_name_plural': 'Document Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='current_published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='documents.documentversion', verbose_name='Current published version'),
        ),
        migrations.CreateModel(
            name='DocumentReadAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Seen and confirmed'), ('declined', 'Seen and declined')], max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_read_acks', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_acknowledgements', to='documents.documentversion')),
            ],
            options={
                'verbose_name': 'Document Read Acknowledgement',
                'verbose_name_plural': 'Document Read Acknowledgements',
                'unique_together': {('version', 'user')},
            },
        ),
        migrations.CreateModel(
            name='DocumentPublishPopupAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_publish_popup_acks', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_popup_acks', to='documents.documentversion')),
            ],
            options={
                'unique_together': {('version', 'user')},
            },
        ),
    ]
