# Generated by Django 6.0.4 on 2026-07-03 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_rebuild_legacy_documents_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='documents.documentcategory', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='documentcategory',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='documents_category_parent_name_uniq'),
        ),
    ]
