# Generated by Django 6.0.4 on 2026-07-23 08:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0023_chemicals_module'),
        ('tasks', '0033_chemicals_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cas_number', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='CAS number')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Name')),
                ('iupac_name', models.CharField(blank=True, max_length=500, verbose_name='IUPAC name')),
                ('molecular_formula', models.CharField(blank=True, max_length=200, verbose_name='Molecular formula')),
                ('pubchem_cid', models.PositiveIntegerField(blank=True, null=True, verbose_name='PubChem CID')),
                ('ghs_signal_word', models.CharField(blank=True, help_text='e.g. Danger, Warning (from PubChem / GHS).', max_length=32, verbose_name='GHS signal word')),
                ('ghs_hazard_codes', models.TextField(blank=True, help_text='Comma-separated H-codes, e.g. H225, H319.', verbose_name='GHS hazard codes')),
                ('ghs_pictograms', models.TextField(blank=True, help_text='Comma-separated pictogram codes or labels.', verbose_name='GHS pictograms')),
                ('is_hazardous', models.BooleanField(db_index=True, default=False, help_text='Set according to the institute hazard threshold in Global Settings.', verbose_name='Classified as hazardous (Gefahrstoff)')),
                ('hazard_classification_notes', models.TextField(blank=True, verbose_name='Classification notes')),
                ('safety_data_sheet', models.FileField(blank=True, max_length=255, null=True, upload_to='chemicals/sds/%Y/%m/', verbose_name='Safety data sheet (local copy)')),
                ('sds_source_url', models.URLField(blank=True, verbose_name='SDS source URL')),
                ('pubchem_raw', models.JSONField(blank=True, default=dict, verbose_name='PubChem raw data')),
                ('last_lookup_at', models.DateTimeField(blank=True, null=True, verbose_name='Last API lookup')),
                ('lookup_error', models.TextField(blank=True, verbose_name='Last lookup error')),
            ],
            options={
                'verbose_name': 'Chemical',
                'verbose_name_plural': 'Chemicals',
                'ordering': ['cas_number'],
                'permissions': [('view_chemical_workgroup', 'Can view chemicals linked to own workgroup items'), ('view_all_chemicals', 'Can view all chemicals institute-wide'), ('manage_chemical_workgroup', 'Can manage chemicals linked to own workgroup items'), ('manage_all_chemicals', 'Can manage all chemicals institute-wide')],
            },
        ),
        migrations.CreateModel(
            name='ChemicalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Item ID')),
                ('ordered_at', models.DateField(blank=True, null=True, verbose_name='Order date')),
                ('status', models.CharField(choices=[('draft', 'Draft (ordered, not delivered)'), ('active', 'Active (delivered / in inventory)'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='Product / trade name')),
                ('quantity_range', models.CharField(choices=[('lt_1', '< 1 kg / L'), ('1_10', '1–10 kg / L'), ('10_100', '10–100 kg / L'), ('gt_100', '> 100 kg / L'), ('unknown', 'Unknown / not set')], default='unknown', max_length=20, verbose_name='Quantity range in use')),
                ('work_area', models.CharField(blank=True, help_text='Areas where employees may be exposed (GefStoffV §6).', max_length=255, verbose_name='Work area / exposure area')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='chemicals.chemical', verbose_name='Chemical')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_chemical_items', to='hr.employee', verbose_name='Ordered by')),
                ('purchase_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_item', to='tasks.purchaseitem', verbose_name='Purchase order item')),
                ('storage_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_items', to='hr.roomstorageitem', verbose_name='Storage location (cabinet / shelf / …)')),
                ('storage_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_items', to='hr.room', verbose_name='Storage room')),
                ('workgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_items', to='hr.workgroup', verbose_name='Work group')),
            ],
            options={
                'verbose_name': 'Chemical item',
                'verbose_name_plural': 'Chemical items',
                'ordering': ['-created_at'],
                'permissions': [('view_own_chemical_items', 'Can view own chemical items (as orderer)'), ('view_workgroup_chemical_items', 'Can view chemical items of own workgroups'), ('view_all_chemical_items', 'Can view all chemical items institute-wide'), ('manage_own_chemical_items', 'Can manage own chemical items (as orderer)'), ('manage_workgroup_chemical_items', 'Can manage chemical items of own workgroups'), ('manage_all_chemical_items', 'Can manage all chemical items institute-wide')],
            },
        ),
    ]
