# Generated by Django 6.0.4 on 2026-07-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_chemicals_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='shelf_life_months',
            field=models.PositiveIntegerField(blank=True, help_text='Typical shelf life in months. Used to auto-calculate MHD on chemical items (from delivery date). Leave empty if unknown.', null=True, verbose_name='Shelf life (months)'),
        ),
        migrations.AddField(
            model_name='chemicalitem',
            name='mhd',
            field=models.DateField(blank=True, db_index=True, help_text='Mindesthaltbarkeitsdatum. Auto-filled from delivery date + chemical shelf life when empty; can be overridden manually.', null=True, verbose_name='MHD (best before)'),
        ),
    ]
