# Generated by Django 6.0.4 on 2026-07-23 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0002_shelf_life_and_mhd'),
        ('hr', '0024_room_chemical_work_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicalitem',
            name='storage_room',
            field=models.ForeignKey(blank=True, help_text='Only rooms that have a storage location (cabinet/shelf/…) are selectable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_storage_items', to='hr.room', verbose_name='Storage room'),
        ),
        migrations.AlterField(
            model_name='chemicalitem',
            name='work_area',
            field=models.ForeignKey(blank=True, help_text='Room where employees may be exposed (GefStoffV §6). Only rooms marked as Chemical work areas are selectable.', limit_choices_to={'chemical': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemical_work_area_items', to='hr.room', verbose_name='Work area / exposure area'),
        ),
    ]
