# Generated by Django 6.0.4 on 2026-09-23 10:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0034_contract_salary_snapshot_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature')], max_length=16, verbose_name='Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('page_url', models.CharField(blank=True, help_text='URL or path of the page the report refers to.', max_length=500, verbose_name='Page URL')),
                ('screenshot', models.FileField(blank=True, max_length=255, null=True, upload_to='feedback/screenshots/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Screenshot')),
                ('status', models.CharField(choices=[('open', 'Open'), ('planned', 'Will be done'), ('done', 'Done')], db_index=True, default='open', max_length=16, verbose_name='Status')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Target date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_items', to='hr.employee', verbose_name='Reported by')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_sources', to='feedback.feedbackitem', verbose_name='Merged into')),
            ],
            options={
                'verbose_name': 'Bug or feature',
                'verbose_name_plural': 'Bugs & Features',
                'ordering': ['-created_at', '-pk'],
                'permissions': [('manage_feedback', 'Can manage bugs and features')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('body', models.TextField(verbose_name='Comment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_comments', to='hr.employee', verbose_name='Author')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.feedbackitem', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Feedback comment',
                'verbose_name_plural': 'Feedback comments',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_votes', to='hr.employee', verbose_name='Employee')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='feedback.feedbackitem', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Feedback vote',
                'verbose_name_plural': 'Feedback votes',
                'constraints': [models.UniqueConstraint(fields=('item', 'employee'), name='feedback_vote_item_employee_uniq')],
            },
        ),
    ]
