# Generated by Django 6.0.4 on 2026-08-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0027_fundingallocation_job_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCustomDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('day', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('mode', models.CharField(choices=[('always', 'Always a holiday'), ('except_and', 'Holiday unless leave immediately before AND after'), ('except_or', 'Holiday unless leave immediately before OR after')], default='always', max_length=20, verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Custom holiday (Brauchtum)',
                'verbose_name_plural': 'Custom holidays (Brauchtum)',
                'ordering': ['day'],
                'constraints': [models.UniqueConstraint(fields=('day',), name='holiday_custom_day_uniq')],
            },
        ),
        migrations.CreateModel(
            name='HolidayEntitlementRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('weekdays', models.PositiveSmallIntegerField(verbose_name='Workdays per week')),
                ('contract_months', models.PositiveSmallIntegerField(verbose_name='Contract months in year')),
                ('days', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Days')),
            ],
            options={
                'verbose_name': 'Holiday entitlement rate',
                'verbose_name_plural': 'Holiday entitlement rates',
                'constraints': [models.UniqueConstraint(fields=('weekdays', 'contract_months'), name='holiday_entitlement_rate_uniq')],
            },
        ),
        migrations.CreateModel(
            name='HolidayProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('works_monday', models.BooleanField(default=True, verbose_name='Monday')),
                ('works_tuesday', models.BooleanField(default=True, verbose_name='Tuesday')),
                ('works_wednesday', models.BooleanField(default=True, verbose_name='Wednesday')),
                ('works_thursday', models.BooleanField(default=True, verbose_name='Thursday')),
                ('works_friday', models.BooleanField(default=True, verbose_name='Friday')),
                ('share_with_institute', models.BooleanField(default=False, verbose_name='Show my holidays on the institute Gantt chart')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='holidays/signatures/', verbose_name='Signature')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_profile', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Holiday Profile',
                'verbose_name_plural': 'Holiday Profiles',
            },
        ),
        migrations.CreateModel(
            name='HolidayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('start_date', models.DateField(verbose_name='From')),
                ('end_date', models.DateField(verbose_name='Until')),
                ('day_count', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Vacation days')),
                ('counted_dates', models.JSONField(blank=True, default=list, verbose_name='Counted dates')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('kind', models.CharField(choices=[('original', 'Original'), ('amendment', 'Amendment')], default='original', max_length=20, verbose_name='Kind')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('rejection_comment', models.TextField(blank=True, verbose_name='Rejection comment')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted at')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Decided at')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='holidays/pdfs/', verbose_name='Generated PDF')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holiday_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Decided by')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_requests', to='hr.employee', verbose_name='Employee')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='holidays.holidayrequest', verbose_name='Amends request')),
            ],
            options={
                'verbose_name': 'Holiday Request',
                'verbose_name_plural': 'Holiday Requests',
                'ordering': ['-start_date', '-pk'],
                'permissions': [('approve_workgroup_holiday', 'Can approve holiday requests in own workgroups'), ('approve_all_holiday', 'Can approve holiday requests institute-wide')],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='HolidayYearEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('days', models.DecimalField(decimal_places=1, max_digits=6, verbose_name='Entitlement (days)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_entitlements', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Holiday Year Entitlement',
                'verbose_name_plural': 'Holiday Year Entitlements',
                'constraints': [models.UniqueConstraint(fields=('employee', 'year'), name='holiday_entitlement_employee_year_uniq')],
            },
        ),
    ]
