# Generated by Django 6.0.4 on 2026-05-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Building Number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Building Name')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('employee_number', models.CharField(max_length=20, unique=True, verbose_name='Employee Number')),
                ('prefix', models.CharField(blank=True, max_length=20, verbose_name='Prefix / Title')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('D', 'Diverse'), ('X', 'Not specified')], default='X', max_length=1, verbose_name='Gender')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='Country of Origin')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, verbose_name='Place of Birth')),
                ('email_professional', models.EmailField(blank=True, max_length=254, verbose_name='Professional Email')),
                ('email_private', models.EmailField(blank=True, max_length=254, verbose_name='Private Email')),
                ('google_account', models.EmailField(blank=True, max_length=254, verbose_name='Google Account')),
                ('private_phone_number', models.CharField(blank=True, max_length=30, verbose_name='Private Phone')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='Office Phone')),
                ('street', models.CharField(blank=True, max_length=100, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='House Number')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Postal Code')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Germany', max_length=100, verbose_name='Country')),
                ('scan_of_contract', models.FileField(blank=True, null=True, upload_to='contract_scans/', verbose_name='Scan of Contract')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pictures/', verbose_name='Profile Picture')),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Salary (â‚¬)')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='finances.costcenter', verbose_name='Cost Center')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pay_scale_group', models.CharField(max_length=50, verbose_name='Pay Scale Group')),
                ('experience_level', models.PositiveSmallIntegerField(verbose_name='Experience Level')),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Weekly Working Hours')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('comments', models.TextField(blank=True, verbose_name='Contract Comments')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['employee', '-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='FundingAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('weekly_hours_allocated', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Allocated Weekly Hours')),
                ('start_date', models.DateField(verbose_name='Valid From')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Valid Until')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='hr.employee', verbose_name='Employee')),
                ('wbs_element', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finances.wbselement', verbose_name='WBS Element')),
            ],
            options={
                'verbose_name': 'Funding Allocation',
                'verbose_name_plural': 'Funding Allocations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('room_number', models.CharField(max_length=50, verbose_name='Room Number')),
                ('colloquial_name', models.CharField(blank=True, max_length=100, verbose_name='Colloquial Name')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hr.building', verbose_name='Building')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['building__number', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('phone_number', models.CharField(max_length=30, verbose_name='Phone Number')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='hr.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Phone Number',
                'verbose_name_plural': 'Phone Numbers',
                'ordering': ['room', 'phone_number'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hr.room', verbose_name='Room'),
        ),
        migrations.CreateModel(
            name='SalarySupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_supplements', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Salary Supplement',
                'verbose_name_plural': 'Salary Supplements',
                'ordering': ['employee', '-created_at'],
            },
        ),
    ]


