# Generated by Django 6.0.4 on 2026-05-13 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text="Kurzbezeichnung, z.B. 'AI-Lab', 'MedTech-Team'", max_length=80, unique=True)),
                ('long_name', models.CharField(help_text='VollstÃ¤ndiger Name der Arbeitsgruppe', max_length=200)),
                ('members', models.ManyToManyField(blank=True, related_name='workgroups', to=settings.AUTH_USER_MODEL, verbose_name='Mitglieder')),
                ('pi', models.ForeignKey(help_text='Der leitende Wissenschaftler dieser Gruppe', on_delete=django.db.models.deletion.PROTECT, related_name='led_workgroups', to='hr.employee', verbose_name='Principal Investigator')),
            ],
            options={
                'verbose_name': 'Workgroup',
                'verbose_name_plural': 'Workgroups',
                'ordering': ['short_name'],
            },
        ),
    ]


