# Generated by Django 6.0.4 on 2026-05-13 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_workgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='workgroups', to='hr.employee', verbose_name='Mitglieder'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_workgroups', to='hr.employee', verbose_name='Principal Investigator'),
        ),
    ]


