# Generated by Django 6.0.4 on 2026-05-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_alter_workgroup_members_alter_workgroup_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='job_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Job Number'),
        ),
    ]


