# Generated by Django 6.0.4 on 2026-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_contract_job_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Salary (€)'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='long_name',
            field=models.CharField(help_text='Vollständiger Name der Arbeitsgruppe', max_length=200),
        ),
    ]
