# Generated by Django 6.0.4 on 2026-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_alter_employee_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['number'], 'permissions': [('manage_location', 'Can manage buildings, rooms and phones')], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_view_employees', 'Can view employee list and details'), ('manage_employee', 'Can manage employees (create and fully edit)')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='workgroup',
            options={'ordering': ['short_name'], 'permissions': [('manage_working_group', 'Can manage working groups')], 'verbose_name': 'Workgroup', 'verbose_name_plural': 'Workgroups'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Office Phone'),
        ),
    ]
