# Generated by Django 6.0.4 on 2026-07-03 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_building_options_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('document_type', models.CharField(choices=[('application', 'Application / Bewerbung'), ('cv', 'Curriculum Vitae / Lebenslauf'), ('measles_proof', 'Measles Vaccination Proof / Nachweis Masernschutzimpfung'), ('scan_of_contract', 'Scan of Contract / Vertragsscan'), ('profile_picture', 'Profile Picture / Profilbild')], max_length=30, verbose_name='Document Type')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='hr.employee', verbose_name='Employee')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_document_versions', to='hr.employee', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Employee Document Version',
                'verbose_name_plural': 'Employee Document Versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
