# Generated by Django 6.0.4 on 2026-07-08 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hr', '0007_personnel_recruitment_and_document_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='workgroup',
            name='auth_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workgroup', to='auth.group', verbose_name='Django group'),
        ),
    ]
