# Generated by Django 6.0.4 on 2026-07-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_employee_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='experience_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Experience Level'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='pay_scale_group',
            field=models.CharField(blank=True, max_length=50, verbose_name='Pay Scale Group'),
        ),
    ]
