# Generated by Django 6.0.4 on 2026-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_remove_personnel_estimate'),
        ('hr', '0011_recruitment_working_as_and_optional_contract_payscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingallocation',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='funding_allocations', to='finances.costcenter', verbose_name='Cost Center'),
        ),
        migrations.AlterField(
            model_name='fundingallocation',
            name='wbs_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finances.wbselement', verbose_name='WBS Element'),
        ),
        migrations.AddConstraint(
            model_name='fundingallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cost_center__isnull', True), ('wbs_element__isnull', False)), models.Q(('cost_center__isnull', False), ('wbs_element__isnull', True)), _connector='OR'), name='funding_allocation_one_target'),
        ),
    ]
