# Generated by Django 6.0.4 on 2026-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_funding_percentage_and_plan_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='import_completed',
            field=models.BooleanField(default=False, help_text='True when imported data confirms the administration process for this employee is complete.', verbose_name='Import completed'),
        ),
    ]
