# Generated by Django 6.0.4 on 2026-07-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_import_completed_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='import_completed',
        ),
        migrations.AddField(
            model_name='fundingallocation',
            name='import_completed',
            field=models.BooleanField(default=False, help_text='True when imported data confirms the administration process for this funding allocation is complete.', verbose_name='Import completed'),
        ),
    ]
