# Generated by Django 6.0.4 on 2026-07-20 13:57

from django.db import migrations, models
from django.utils import timezone


def deactivate_past_end_dates(apps, schema_editor):
    """Set is_active=False where end date is already in the past."""
    today = timezone.now().date()
    Contract = apps.get_model('hr', 'Contract')
    FundingAllocation = apps.get_model('hr', 'FundingAllocation')
    Contract.objects.filter(valid_until__lt=today).update(is_active=False)
    FundingAllocation.objects.filter(end_date__lt=today).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_funding_allocation_import_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Yes/No. Can be set manually. Automatically set to No when '
                    'Valid Until is in the past.'
                ),
                verbose_name='Active',
            ),
        ),
        migrations.AddField(
            model_name='fundingallocation',
            name='is_active',
            field=models.BooleanField(
                default=True,
                help_text=(
                    'Yes/No. Can be set manually. Automatically set to No when '
                    'Valid Until is in the past.'
                ),
                verbose_name='Active',
            ),
        ),
        migrations.RunPython(deactivate_past_end_dates, migrations.RunPython.noop),
    ]
