# Generated by Django 6.0.4 on 2026-07-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_salarysupplement_percentage_and_fixed_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['employee', 'valid_from', 'valid_until', 'pk'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('can_view_employees', 'Can view employees in shared workgroups'), ('manage_employee', 'Can manage employees in shared workgroups (create and edit)'), ('can_view_all_employees', 'Can view all employees institute-wide (ignore workgroup scope)'), ('manage_all_employees', 'Can manage all employees institute-wide (ignore workgroup scope)')], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='fundingallocation',
            options={'ordering': ['start_date', 'end_date', 'pk'], 'verbose_name': 'Funding Allocation', 'verbose_name_plural': 'Funding Allocations'},
        ),
    ]
