# Generated by Django 6.0.4 on 2026-07-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0022_employee_workgroup_and_all_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomStorageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=120, verbose_name='Storage name')),
                ('storage_type', models.CharField(blank=True, help_text='e.g. cabinet, fridge, shelf, gas store', max_length=80, verbose_name='Type')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_items', to='hr.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room storage item',
                'verbose_name_plural': 'Room storage items',
                'ordering': ['room', 'name'],
                'unique_together': {('room', 'name')},
            },
        ),
    ]
