# Generated by Django 6.0.4 on 2026-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0023_chemicals_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='chemical',
            field=models.BooleanField(db_index=True, default=False, help_text='If set, this room can be selected as a chemical work area / exposure area on chemical inventory items.', verbose_name='Chemical (work area)'),
        ),
    ]
