# Generated by Django 6.0.4 on 2026-07-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0024_room_chemical_work_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='monthly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly salary the person would receive at 100% working time (full-time reference). Part-time hours are applied only when calculating true costs. Salary supplements are added on top.', max_digits=10, null=True, verbose_name='Monthly Salary (100% workload)'),
        ),
        migrations.AlterField(
            model_name='salarysupplement',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed euro amount per month at 100% workload (scaled with weekly hours in true costs). Leave empty if using a percentage.', max_digits=10, null=True, verbose_name='Fixed amount (€)'),
        ),
        migrations.AlterField(
            model_name='salarysupplement',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Percentage of the contract's 100% monthly salary. Leave empty if using a fixed amount.", max_digits=5, null=True, verbose_name='Percentage (%)'),
        ),
    ]
