# Generated by Django 6.0.4 on 2026-07-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_salary_true_cost_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='check_needed',
            field=models.BooleanField(default=False, help_text='Manual review required for this contract (e.g. after funding-report import).', verbose_name='Check needed'),
        ),
        migrations.AddField(
            model_name='employee',
            name='check_needed',
            field=models.BooleanField(default=False, help_text='Manual review required. A Django login user may only be linked when this flag is No.', verbose_name='Check needed'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='Employee was created from a funding-report import and is still pending review. Visible in the employee list.', verbose_name='Pending'),
        ),
    ]
