# Generated by Django 6.0.4 on 2026-09-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_occupation_salary_tables'),
        ('hr', '0032_hide_extern_pi'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_table',
            field=models.ForeignKey(blank=True, help_text='TV-L when empty, unless the job specifies an occupational table.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.occupationsalarytable', verbose_name='Salary table'),
        ),
    ]
