# Generated by Django 6.0.4 on 2026-09-29 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0034_contract_salary_snapshot_help'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('kind', models.CharField(choices=[('google_calendar', 'Google Calendar')], db_index=True, max_length=40, verbose_name='Kind')),
                ('identifier', models.CharField(blank=True, default='', help_text='External account identifier (e.g. Gmail address).', max_length=254, verbose_name='Identifier')),
                ('status', models.CharField(choices=[('active', 'Shared'), ('removed', 'Removed'), ('error', 'Error')], db_index=True, default='removed', max_length=20, verbose_name='Status')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Detail')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last synced at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='hr.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Employee external account',
                'verbose_name_plural': 'Employee external accounts',
                'ordering': ['employee__last_name', 'employee__first_name', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'kind'), name='hr_employeeexternalaccount_employee_kind')],
            },
        ),
    ]
