# Generated by Django 6.0.4 on 2026-09-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0035_google_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexternalaccount',
            name='lists',
            field=models.JSONField(blank=True, default=list, help_text='Mailing lists last synced for this account.', verbose_name='Lists'),
        ),
        migrations.AddField(
            model_name='workgroup',
            name='sympa_list',
            field=models.EmailField(blank=True, default='', help_text='Workgroup list address, e.g. ag-foo@listen.uni-bonn.de. Leave blank if none.', max_length=254, verbose_name='Sympa mailing list'),
        ),
        migrations.AlterField(
            model_name='employeeexternalaccount',
            name='kind',
            field=models.CharField(choices=[('google_calendar', 'Google Calendar'), ('sympa', 'Sympa')], db_index=True, max_length=40, verbose_name='Kind'),
        ),
    ]
