# Generated by Django 6.0.4 on 2026-05-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('cost_center', models.CharField(max_length=50, unique=True, verbose_name='Cost Center')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['cost_center'],
            },
        ),
        migrations.CreateModel(
            name='WBSElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('wbs_code', models.CharField(max_length=50, unique=True, verbose_name='WBS Element')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('comment', models.TextField(blank=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'WBS Element',
                'verbose_name_plural': 'WBS Elements',
                'ordering': ['wbs_code'],
            },
        ),
        migrations.CreateModel(
            name='WBSElementInitialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Initial Balance')),
            ],
            options={
                'verbose_name': 'WBS Element Initial Balance',
                'verbose_name_plural': 'WBS Element Initial Balances',
                'ordering': ['wbs_element', '-year'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterInitialBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Initial Balance')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_balances', to='finances.costcenter', verbose_name='Cost Center')),
            ],
            options={
                'verbose_name': 'Cost Center Initial Balance',
                'verbose_name_plural': 'Cost Center Initial Balances',
                'ordering': ['cost_center', '-year'],
            },
        ),
        migrations.CreateModel(
            name='PayScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pay_scale_group', models.CharField(max_length=50, verbose_name='Pay Scale Group')),
                ('experience_level', models.PositiveSmallIntegerField(verbose_name='Experience Level')),
                ('monthly_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monthly Salary')),
                ('effective_as_of', models.DateField(verbose_name='Effective As Of')),
            ],
            options={
                'verbose_name': 'Pay Scale',
                'verbose_name_plural': 'Pay Scales',
                'ordering': ['pay_scale_group', 'experience_level'],
                'unique_together': {('pay_scale_group', 'experience_level', 'effective_as_of')},
            },
        ),
    ]


