# Generated by Django 6.0.4 on 2026-05-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbselement',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_wbs_elements', to='hr.employee', verbose_name='Responsible Person'),
        ),
        migrations.AddField(
            model_name='wbselementinitialbalance',
            name='wbs_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_balances', to='finances.wbselement', verbose_name='WBS Element'),
        ),
        migrations.AlterUniqueTogether(
            name='costcenterinitialbalance',
            unique_together={('cost_center', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='wbselementinitialbalance',
            unique_together={('wbs_element', 'year')},
        ),
    ]


