# Generated by Django 6.0.4 on 2026-07-01 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
        ('hr', '0005_alter_employee_monthly_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbselement',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_elements', to='hr.workgroup', verbose_name='Work Group'),
        ),
    ]
