# Generated by Django 6.0.4 on 2026-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_wbselement_work_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payscale',
            options={'ordering': ['pay_scale_group', 'experience_level'], 'permissions': [('import_pay_scale', 'Can import pay scales / TV-L')], 'verbose_name': 'Pay Scale', 'verbose_name_plural': 'Pay Scales'},
        ),
        migrations.AlterModelOptions(
            name='wbselement',
            options={'ordering': ['wbs_code'], 'permissions': [('view_psp_element', 'Can view individual PSP elements'), ('manage_psp_element', 'Can manage PSP elements'), ('view_psp_overview', 'Can view PSP overview with bookings and costs')], 'verbose_name': 'PSP Element', 'verbose_name_plural': 'PSP Elements'},
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='wbs_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='PSP Element'),
        ),
    ]
