# Generated by Django 6.0.4 on 2026-07-17 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_remove_personnel_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='third_party_funding_commitment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='finances/cost_center/third_party_funding/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Drittmittelzusage'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='third_party_funding_commitment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='finances/psp/third_party_funding/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Drittmittelzusage'),
        ),
    ]
