# Generated by Django 6.0.4 on 2026-07-17 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_filefield_max_length_third_party_funding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wbselementyearestimate',
            name='animal_costs_estimate',
        ),
        migrations.RemoveField(
            model_name='wbselementyearestimate',
            name='consumables_estimate',
        ),
        migrations.RemoveField(
            model_name='wbselementyearestimate',
            name='funding',
        ),
        migrations.RemoveField(
            model_name='wbselementyearestimate',
            name='travel_estimate',
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_animal_husbandry_costs',
            field=models.BooleanField(default=False, verbose_name='.7 - Tierhaltungskosten / Animal husbandry costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_domestic_travel_costs',
            field=models.BooleanField(default=False, verbose_name='.3 - Reisekosten Inland / Domestic travel costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_foreign_travel_costs',
            field=models.BooleanField(default=False, verbose_name='.4 - Reisekosten Ausland / Foreign travel costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_material_costs',
            field=models.BooleanField(default=False, verbose_name='.1 - Sachkosten / Material costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_personnel_costs',
            field=models.BooleanField(default=False, verbose_name='.2 - Personalkosten / Personnel costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_publication_costs',
            field=models.BooleanField(default=False, verbose_name='.6 - Publikationskosten / Publication costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_third_party_investments',
            field=models.BooleanField(default=False, verbose_name='.5 - Drittmittel-Investitionen / Third-party investments'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='has_transfer_to_third_parties',
            field=models.BooleanField(default=False, verbose_name='.8 - Weitergabe an Dritte / Transfer to third parties'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='animal_husbandry_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.7 - Tierhaltungskosten / Animal husbandry costs'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='domestic_travel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.3 - Reisekosten Inland / Domestic travel costs'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='foreign_travel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.4 - Reisekosten Ausland / Foreign travel costs'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='material_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.1 - Sachkosten / Material costs'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='personnel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.2 - Personalkosten / Personnel costs'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='publication_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.6 - Publikationskosten / Publication costs'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='third_party_investments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.5 - Drittmittel-Investitionen / Third-party investments'),
        ),
        migrations.AddField(
            model_name='wbselementyearestimate',
            name='transfer_to_third_parties',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.8 - Weitergabe an Dritte / Transfer to third parties'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='third_party_funder_identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Third-party funder identifier'),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='third_party_funding_commitment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='finances/cost_center/third_party_funding/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Third-party funding commitment'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='third_party_funder_identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='Third-party funder identifier'),
        ),
        migrations.AlterField(
            model_name='wbselement',
            name='third_party_funding_commitment',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='finances/psp/third_party_funding/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif', 'webp'])], verbose_name='Third-party funding commitment'),
        ),
    ]
