# Generated by Django 6.0.4 on 2026-07-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_psp_cost_types_year_estimates'),
    ]

    operations = [
        migrations.CreateModel(
            name='WBSElementTrueYearlySpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Year / Period')),
                ('material_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.1 - Sachkosten / Material costs')),
                ('personnel_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.2 - Personalkosten / Personnel costs')),
                ('domestic_travel_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.3 - Reisekosten Inland / Domestic travel costs')),
                ('foreign_travel_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.4 - Reisekosten Ausland / Foreign travel costs')),
                ('third_party_investments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.5 - Drittmittel-Investitionen / Third-party investments')),
                ('publication_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.6 - Publikationskosten / Publication costs')),
                ('animal_husbandry_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.7 - Tierhaltungskosten / Animal husbandry costs')),
                ('transfer_to_third_parties', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.8 - Weitergabe an Dritte / Transfer to third parties')),
                ('wbs_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_yearly_spendings', to='finances.wbselement', verbose_name='PSP Element')),
            ],
            options={
                'verbose_name': 'PSP Element True Yearly Spending',
                'verbose_name_plural': 'PSP Element True Yearly Spendings',
                'ordering': ['year'],
                'unique_together': {('wbs_element', 'year')},
            },
        ),
    ]
