# Generated by Django 6.0.4 on 2026-07-17 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_psp_true_yearly_spending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcenter',
            name='third_party_funder_identifier',
        ),
        migrations.RemoveField(
            model_name='costcenter',
            name='third_party_funding_commitment',
        ),
        migrations.RemoveField(
            model_name='costcenteryearestimate',
            name='animal_costs_estimate',
        ),
        migrations.RemoveField(
            model_name='costcenteryearestimate',
            name='consumables_estimate',
        ),
        migrations.RemoveField(
            model_name='costcenteryearestimate',
            name='travel_estimate',
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_animal_husbandry_costs',
            field=models.BooleanField(default=False, verbose_name='Tierhaltungskosten / Animal husbandry costs'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_domestic_travel_costs',
            field=models.BooleanField(default=False, verbose_name='Reisekosten Inland / Domestic travel costs'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_foreign_travel_costs',
            field=models.BooleanField(default=False, verbose_name='Reisekosten Ausland / Foreign travel costs'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_material_costs',
            field=models.BooleanField(default=False, verbose_name='Sachkosten / Material costs'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_personnel_costs',
            field=models.BooleanField(default=False, verbose_name='Personalkosten / Personnel costs'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_publication_costs',
            field=models.BooleanField(default=False, verbose_name='Publikationskosten / Publication costs'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_third_party_investments',
            field=models.BooleanField(default=False, verbose_name='Drittmittel-Investitionen / Third-party investments'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='has_transfer_to_third_parties',
            field=models.BooleanField(default=False, verbose_name='Weitergabe an Dritte / Transfer to third parties'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='animal_husbandry_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.7 - Tierhaltungskosten / Animal husbandry costs'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='domestic_travel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.3 - Reisekosten Inland / Domestic travel costs'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='foreign_travel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.4 - Reisekosten Ausland / Foreign travel costs'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='material_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.1 - Sachkosten / Material costs'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='personnel_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.2 - Personalkosten / Personnel costs'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='publication_costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.6 - Publikationskosten / Publication costs'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='third_party_investments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.5 - Drittmittel-Investitionen / Third-party investments'),
        ),
        migrations.AddField(
            model_name='costcenteryearestimate',
            name='transfer_to_third_parties',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.8 - Weitergabe an Dritte / Transfer to third parties'),
        ),
        migrations.CreateModel(
            name='CostCenterTrueYearlySpending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('year', models.PositiveIntegerField(verbose_name='Year / Period')),
                ('material_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.1 - Sachkosten / Material costs')),
                ('personnel_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.2 - Personalkosten / Personnel costs')),
                ('domestic_travel_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.3 - Reisekosten Inland / Domestic travel costs')),
                ('foreign_travel_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.4 - Reisekosten Ausland / Foreign travel costs')),
                ('third_party_investments', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.5 - Drittmittel-Investitionen / Third-party investments')),
                ('publication_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.6 - Publikationskosten / Publication costs')),
                ('animal_husbandry_costs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.7 - Tierhaltungskosten / Animal husbandry costs')),
                ('transfer_to_third_parties', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='.8 - Weitergabe an Dritte / Transfer to third parties')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='true_yearly_spendings', to='finances.costcenter', verbose_name='Cost Center')),
            ],
            options={
                'verbose_name': 'Cost Center True Yearly Spending',
                'verbose_name_plural': 'Cost Center True Yearly Spendings',
                'ordering': ['year'],
                'unique_together': {('cost_center', 'year')},
            },
        ),
    ]
