# Generated by Django 6.0.4 on 2026-07-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_cost_type_9_obligo_date_of_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenterobligo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='costcenterobligo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='wbselementobligo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wbselementobligo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
