# Generated by Django 6.0.4 on 2026-07-20 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_obligo_base_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbselement',
            options={'ordering': ['wbs_code'], 'permissions': [('view_psp_element', 'Can view individual PSP elements'), ('manage_psp_element', 'Can manage PSP elements'), ('view_psp_overview', 'Can view PSP overview with bookings and costs'), ('import_third_party_funding_report', 'Can import third-party funding reports')], 'verbose_name': 'PSP Element', 'verbose_name_plural': 'PSP Elements'},
        ),
        migrations.AddField(
            model_name='costcenterobligo',
            name='personal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Personalobligo'),
        ),
        migrations.AddField(
            model_name='wbselementobligo',
            name='personal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Personalobligo'),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('business_area', models.CharField(blank=True, max_length=255, verbose_name='Business area')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Contact Person',
                'verbose_name_plural': 'Contact Persons',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('last_name', 'first_name')},
            },
        ),
        migrations.AddField(
            model_name='costcenter',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='finances.contactperson', verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wbs_elements', to='finances.contactperson', verbose_name='Contact person'),
        ),
    ]
