# Generated by Django 6.0.4 on 2026-07-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_contact_person_obligo_personal_import_perm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactperson',
            options={'ordering': ['last_name', 'first_name'], 'permissions': [('view_contact_person_list', 'Can view contact persons'), ('manage_contact_person', 'Can manage contact persons')], 'verbose_name': 'Contact Person', 'verbose_name_plural': 'Contact Persons'},
        ),
    ]
