# Generated by Django 6.0.4 on 2026-07-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_contact_person_list_manage_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='comments',
            field=models.CharField(blank=True, max_length=400, verbose_name='Comments'),
        ),
    ]
