# Generated by Django 6.0.4 on 2026-07-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_contact_person_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wbselement',
            options={'ordering': ['wbs_code'], 'permissions': [('view_psp_element', 'Can view individual PSP elements in own workgroups'), ('manage_psp_element', 'Can manage PSP elements in own workgroups'), ('view_psp_overview', 'Can view PSP overview for own workgroups'), ('view_all_psp_elements', 'Can view all PSP elements institute-wide (ignore workgroup scope)'), ('manage_all_psp_elements', 'Can manage all PSP elements institute-wide (ignore workgroup scope)'), ('import_third_party_funding_report', 'Can import third-party funding reports')], 'verbose_name': 'PSP Element', 'verbose_name_plural': 'PSP Elements'},
        ),
    ]
