# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_psp_all_and_permission_labels'),
        ('hr', '0026_personnel_import_flags_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='work_group',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='cost_centers',
                to='hr.workgroup',
                verbose_name='Work Group',
            ),
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={
                'ordering': ['cost_center'],
                'permissions': [
                    ('manage_cost_center', 'Can manage cost centers in own workgroups'),
                    (
                        'manage_all_cost_centers',
                        'Can manage all cost centers institute-wide (ignore workgroup scope)',
                    ),
                ],
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
            },
        ),
        migrations.AlterModelOptions(
            name='wbselement',
            options={
                'ordering': ['wbs_code'],
                'permissions': [
                    ('view_psp_element', 'Can view individual PSP elements in own workgroups'),
                    ('manage_psp_element', 'Can manage PSP elements in own workgroups'),
                    ('view_psp_overview', 'Can view PSP overview for own workgroups'),
                    (
                        'view_all_psp_elements',
                        'Can view all PSP elements institute-wide (ignore workgroup scope)',
                    ),
                    (
                        'manage_all_psp_elements',
                        'Can manage all PSP elements institute-wide (ignore workgroup scope)',
                    ),
                    ('import_third_party_funding_report', 'Can import third-party funding reports'),
                ],
                'verbose_name': 'PSP Element',
                'verbose_name_plural': 'Funding analysis',
            },
        ),
    ]
