# Generated by Django 6.0.4 on 2026-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_ensure_cost_center_manage_all_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbselement',
            name='comment_animal_husbandry_costs',
            field=models.TextField(blank=True, verbose_name='Comment – Animal husbandry costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_domestic_travel_costs',
            field=models.TextField(blank=True, verbose_name='Comment – Domestic travel costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_foreign_travel_costs',
            field=models.TextField(blank=True, verbose_name='Comment – Foreign travel costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_internal_service_charges',
            field=models.TextField(blank=True, verbose_name='Comment – Internal service charges'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_material_costs',
            field=models.TextField(blank=True, verbose_name='Comment – Material costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_personnel_costs',
            field=models.TextField(blank=True, verbose_name='Comment – Personnel costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_publication_costs',
            field=models.TextField(blank=True, verbose_name='Comment – Publication costs'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_third_party_investments',
            field=models.TextField(blank=True, verbose_name='Comment – Third-party investments'),
        ),
        migrations.AddField(
            model_name='wbselement',
            name='comment_transfer_to_third_parties',
            field=models.TextField(blank=True, verbose_name='Comment – Transfer to third parties'),
        ),
    ]
